### ISSUE TITLE
header for pages like the FAQ or the Privacy page

### ISSUE THREAD

**Issue by samnet** [bybitapp/www-bytes#4]
We have one same header for the entire site. That's great in a way.

A minor issue is that having anchor links (Team, Product, .. ) for dead end simple pages like FAQ and Privacy pages make little sense.

Is it possible to have a simplified header for this routes? Ideally, this simple header would only have the logo. (no need for a "back" button even, since they open in a new tab anyhow).

**Comment by samnet** [comment]
(Whether it should open in a new tab or not is a matter of debate

https://ux.stackexchange.com/questions/95651/when-to-open-link-in-new-tab

But it is anyways secondary to the point.)

The issue remains the same if it opens in the same tab: try to click on e.g., Team whn u r on the privacy page... we can t have same header there as on main page.

Issue as open as ever.

**Comment by pasupulaphani** [comment]
cool. will think of something simple header

**Comment by Maynkmohta** [comment]
I think we should have a blog section with few 2-3 blogs and once the user
clicks on "Read More" it is redirected to a new page or new tab. But
directly clicking on blogs and moving to a new page can distract the user.
